# Generated by Django 6.0.6 on 2026-07-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_role_appointment_caretakereditrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretakerprofile',
            name='caretaker_code',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='doctor_code',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='patient_code',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
