# Generated by Django 6.0.6 on 2026-07-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_caretakerprofile_caretaker_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
