# Generated by Django 6.0.6 on 2026-07-27 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretakerprofile',
            name='rating_avg',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='caretakerprofile',
            name='reviews_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='rating_avg',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='reviews_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caretaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.caretakerprofile')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.doctorprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
    ]
