# Generated by Django 6.0.6 on 2026-07-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_caretakerprofile_rating_avg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='availability_status',
            field=models.CharField(default='Active Today', max_length=30),
        ),
    ]
