# Generated by Django 6.0.6 on 2026-07-28 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_plain_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('critical', 'Critical Emergency'), ('urgent', 'Urgent Medical Need'), ('moderate', 'Moderate Medical Concern'), ('low', 'Low / General Inquiry')], default='moderate', max_length=20)),
                ('condition_summary', models.TextField(help_text='AI-detected condition description')),
                ('ai_advice', models.TextField(blank=True, help_text='Safety advice given by AI', null=True)),
                ('detected_specialty', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_query', models.TextField(blank=True, help_text='What the patient said/asked', null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('caretaker_notified', models.BooleanField(default=False)),
                ('caretaker_seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'emergency_alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
