# Generated by Django 6.0.6 on 2026-07-28 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_doctorprofile_city_doctorprofile_hospital_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='city',
        ),
    ]
