# Generated by Django 6.0.6 on 2026-07-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_doctorprofile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
