# Generated by Django 6.0.6 on 2026-07-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_appointment_appointment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='prescription_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='prescription_pdf',
            field=models.TextField(blank=True, null=True),
        ),
    ]
