# Generated by Django 6.0.6 on 2026-07-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_appointment_prescription_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_call_active',
            field=models.BooleanField(default=False),
        ),
    ]
