# Generated by Django 6.0.6 on 2026-07-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_appointment_is_call_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_caretaker_added_to_call',
            field=models.BooleanField(default=False),
        ),
    ]
