# Generated by Django 6.0.6 on 2026-07-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_appointment_is_caretaker_added_to_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
