# Generated by Django 6.0.6 on 2026-07-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_signup_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretakerprofile',
            name='availability_status',
            field=models.CharField(default='Active Today', max_length=30),
        ),
    ]
